/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("brewery.controller.java-application-conventions")
    id("org.springframework.boot") version "3.1.0"
}

apply(plugin = "io.spring.dependency-management")

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation(project(":application"))
    implementation("com.ghgande:j2mod:3.1.1")
}

application {
    // Define the main class for the application.
    mainClass.set("brewery.inputs.BreweryServer")
}
